# Generated by Django 5.2.6 on 2025-10-31 17:58

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Asset",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "inventory_code",
                    models.CharField(
                        max_length=100, unique=True, verbose_name="Código de Inventario"
                    ),
                ),
                (
                    "serial_number",
                    models.CharField(
                        max_length=100, unique=True, verbose_name="Número de Serie"
                    ),
                ),
                (
                    "asset_type",
                    models.CharField(
                        choices=[
                            ("NOTEBOOK", "Notebook"),
                            ("DESKTOP", "Desktop"),
                            ("MONITOR", "Monitor"),
                            ("PRINTER", "Impresora"),
                            ("OTHER", "Otro"),
                        ],
                        max_length=50,
                        verbose_name="Tipo de Activo",
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("BODEGA", "En Bodega"),
                            ("ASIGNADO", "Asignado"),
                            ("REPARACION", "En Reparación"),
                            ("DE_BAJA", "De Baja"),
                        ],
                        default="BODEGA",
                        max_length=50,
                        verbose_name="Estado",
                    ),
                ),
                ("brand", models.CharField(blank=True, max_length=100)),
                ("model", models.CharField(blank=True, max_length=100)),
                (
                    "acquisition_date",
                    models.DateField(
                        blank=True, null=True, verbose_name="Fecha de Adquisición"
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name="GraphicsCard",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("model_name", models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name="StorageDevice",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("model", models.CharField(blank=True, max_length=255)),
                ("serial_number", models.CharField(blank=True, max_length=100)),
                (
                    "capacity_gb",
                    models.FloatField(
                        blank=True, null=True, verbose_name="Capacidad (GB)"
                    ),
                ),
                (
                    "free_space_gb",
                    models.FloatField(
                        blank=True, null=True, verbose_name="Espacio Libre (GB)"
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="ComputerDetail",
            fields=[
                (
                    "asset",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        primary_key=True,
                        serialize=False,
                        to="assets.asset",
                    ),
                ),
                (
                    "unique_identifier",
                    models.CharField(
                        blank=True, max_length=255, verbose_name="UUID de BIOS/UEFI"
                    ),
                ),
                (
                    "os_name",
                    models.CharField(
                        blank=True, max_length=100, verbose_name="Nombre SO"
                    ),
                ),
                (
                    "os_version",
                    models.CharField(
                        blank=True, max_length=50, verbose_name="Versión SO"
                    ),
                ),
                (
                    "os_arch",
                    models.CharField(
                        blank=True, max_length=10, verbose_name="Arquitectura SO"
                    ),
                ),
                (
                    "cpu_model",
                    models.CharField(
                        blank=True, max_length=255, verbose_name="Modelo de CPU"
                    ),
                ),
                (
                    "ram_gb",
                    models.FloatField(blank=True, null=True, verbose_name="RAM (GB)"),
                ),
                (
                    "motherboard_manufacturer",
                    models.CharField(
                        blank=True, max_length=100, verbose_name="Fabricante Placa Base"
                    ),
                ),
                (
                    "motherboard_model",
                    models.CharField(
                        blank=True, max_length=100, verbose_name="Modelo Placa Base"
                    ),
                ),
                (
                    "last_updated_by_agent",
                    models.DateTimeField(
                        blank=True,
                        null=True,
                        verbose_name="Última Actualización por Agente",
                    ),
                ),
            ],
        ),
    ]
