# Generated by Django 5.2.6 on 2025-10-31 17:58

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("assets", "0001_initial"),
        ("users", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="asset",
            name="department",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT,
                related_name="assets",
                to="users.department",
                verbose_name="Departamento (Centro de Costo)",
            ),
        ),
        migrations.AddField(
            model_name="asset",
            name="employee",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="assets",
                to="users.employee",
                verbose_name="Empleado Asignado",
            ),
        ),
        migrations.AddField(
            model_name="graphicscard",
            name="asset",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="graphics_cards",
                to="assets.asset",
            ),
        ),
        migrations.AddField(
            model_name="storagedevice",
            name="asset",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="storage_devices",
                to="assets.asset",
            ),
        ),
    ]
