# Generated by Django 5.2.6 on 2025-11-12 23:43

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("assets", "0002_initial"),
        ("users", "0002_alter_customuser_groups_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="asset",
            name="department",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="assets",
                to="users.department",
                verbose_name="Departamento (Centro de Costo)",
            ),
        ),
    ]
