# Generated by Django 5.2.6 on 2025-10-31 17:58

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("assets", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="AuditLog",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("timestamp", models.DateTimeField(auto_now_add=True)),
                ("action", models.CharField(max_length=50)),
                ("target_table", models.CharField(max_length=100)),
                ("target_id", models.PositiveIntegerField()),
                ("details", models.JSONField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name="ComplianceWarning",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("detection_date", models.DateTimeField(auto_now_add=True)),
                ("category", models.CharField(max_length=100)),
                ("description", models.TextField()),
                (
                    "evidence",
                    models.JSONField(
                        blank=True, null=True, verbose_name="Evidencia (ej. rutas)"
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("NUEVA", "Nueva"),
                            ("EN_REVISION", "En Revisión"),
                            ("RESUELTA", "Resuelta"),
                            ("FALSO_POSITIVO", "Falso Positivo"),
                        ],
                        default="NUEVA",
                        max_length=50,
                    ),
                ),
                ("resolution_notes", models.TextField(blank=True)),
            ],
        ),
        migrations.CreateModel(
            name="AssetCheckin",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("checkin_date", models.DateTimeField(auto_now_add=True)),
                ("physical_state", models.CharField(max_length=50)),
                (
                    "performance_satisfaction",
                    models.PositiveIntegerField(blank=True, null=True),
                ),
                ("notes", models.TextField(blank=True)),
                (
                    "asset",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="checkins",
                        to="assets.asset",
                    ),
                ),
            ],
        ),
    ]
