# Generated by Django 5.2.6 on 2025-11-28 20:02

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("auditing", "0003_alter_auditlog_system_user"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="HardwareObsolescenceRules",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "windows_min_version",
                    models.CharField(
                        default="10.0.19041",
                        help_text="Build number (ej: 10.0.19041 para Win10, 10.0.22000 para Win11)",
                        max_length=50,
                        verbose_name="Versión mínima de Windows",
                    ),
                ),
                (
                    "ram_min_gb",
                    models.FloatField(
                        default=4.0,
                        help_text="Equipos con menos RAM se consideran obsoletos",
                        verbose_name="RAM mínima (GB)",
                    ),
                ),
                (
                    "disk_min_free_percent",
                    models.FloatField(
                        default=10.0,
                        help_text="Equipos con menos espacio disponible se consideran en riesgo",
                        verbose_name="Espacio libre mínimo en disco (%)",
                    ),
                ),
                (
                    "enabled",
                    models.BooleanField(
                        default=True,
                        help_text="Desactivar para pausar la detección de hardware obsoleto",
                        verbose_name="Reglas activas",
                    ),
                ),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "updated_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="obsolescence_rules_updates",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "Reglas de Obsolescencia de Hardware",
                "verbose_name_plural": "Reglas de Obsolescencia de Hardware",
            },
        ),
    ]
