# Generated by Django 5.2.6 on 2025-11-29 18:18

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("auditing", "0004_hardwareobsolescencerules"),
    ]

    operations = [
        migrations.AddField(
            model_name="assetcheckin",
            name="completed_at",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="assetcheckin",
            name="requested_at",
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name="assetcheckin",
            name="status",
            field=models.CharField(
                choices=[
                    ("PENDIENTE", "Pendiente"),
                    ("COMPLETADO", "Completado"),
                    ("EXPIRADO", "Expirado"),
                ],
                default="PENDIENTE",
                max_length=20,
            ),
        ),
        migrations.AddField(
            model_name="assetcheckin",
            name="unique_token",
            field=models.CharField(
                db_index=True, default="", max_length=64, unique=True
            ),
        ),
        migrations.AlterField(
            model_name="assetcheckin",
            name="checkin_date",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="assetcheckin",
            name="physical_state",
            field=models.CharField(blank=True, max_length=50),
        ),
    ]
