# Generated by Django 5.2.6 on 2025-11-30 01:20

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        (
            "auditing",
            "0005_assetcheckin_completed_at_assetcheckin_requested_at_and_more",
        ),
    ]

    operations = [
        migrations.AlterField(
            model_name="compliancewarning",
            name="detection_date",
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
