# Generated by Django 5.2.6 on 2025-10-31 17:58

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("assets", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="SoftwareCatalog",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=255)),
                ("developer", models.CharField(blank=True, max_length=255)),
            ],
            options={
                "verbose_name": "Software en Catálogo",
                "verbose_name_plural": "Software en Catálogo",
            },
        ),
        migrations.CreateModel(
            name="Vulnerability",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "cve_id",
                    models.CharField(
                        max_length=50, unique=True, verbose_name="ID de CVE"
                    ),
                ),
                ("description", models.TextField(blank=True)),
                ("severity", models.CharField(max_length=20)),
                ("link_to_details", models.URLField(blank=True, max_length=512)),
            ],
        ),
        migrations.CreateModel(
            name="License",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "license_key",
                    models.TextField(blank=True, verbose_name="Clave de Licencia"),
                ),
                ("purchase_date", models.DateField(blank=True, null=True)),
                ("expiration_date", models.DateField(blank=True, null=True)),
                ("quantity", models.PositiveIntegerField(default=1)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "software",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="licenses",
                        to="software.softwarecatalog",
                    ),
                ),
            ],
        ),
        migrations.AddField(
            model_name="softwarecatalog",
            name="vulnerabilities",
            field=models.ManyToManyField(
                blank=True, related_name="software", to="software.vulnerability"
            ),
        ),
        migrations.CreateModel(
            name="InstalledSoftware",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("version", models.CharField(blank=True, max_length=50)),
                ("install_date", models.DateField(blank=True, null=True)),
                (
                    "asset",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="installed_software",
                        to="assets.asset",
                    ),
                ),
                (
                    "software",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="installations",
                        to="software.softwarecatalog",
                    ),
                ),
            ],
            options={
                "verbose_name": "Software Instalado",
                "verbose_name_plural": "Software Instalado",
                "unique_together": {("asset", "software")},
            },
        ),
        migrations.AlterUniqueTogether(
            name="softwarecatalog",
            unique_together={("name", "developer")},
        ),
    ]
