# Generated by Django 5.2.6 on 2025-11-07 23:25

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("software", "0001_initial"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="installedsoftware",
            options={
                "verbose_name": "Installed Software",
                "verbose_name_plural": "Installed Softwares",
            },
        ),
        migrations.AlterModelOptions(
            name="softwarecatalog",
            options={
                "verbose_name": "Software catalog",
                "verbose_name_plural": "software catalogs",
            },
        ),
        migrations.AddField(
            model_name="installedsoftware",
            name="license",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="installations",
                to="software.license",
            ),
        ),
    ]
